% Experiment with TouchScreen
% 2020 by Clara Kuper
% check timing

% System setup
% Clear the workspace and the screen
sca;
clear all;
clear mex;
clear functions;
% cursor goes home, command window scrolled up
home;

% Which experiment are we running?
expCode = 'MI';
sprintf('Now running experiment %s',expCode);

% add the functions folder to searchpath and define storage paths
addpath('0_Functions/','Data/');

% Unify keys in case sb codes with a different system
KbName('UnifyKeyNames');

% Here we call some default settings for setting up Psychtoolbox

PsychDefaultSetup(2);

% Init random
rand('seed', sum(100 * clock));

%start a timer for the experiment
tic;

% define some settings for the experiment
global settings visual design;

settings.TEST   = 1; % Track or no Track
settings.SYNCTEST = 1; % run synchtest or not
settings.id = 0;
settings.feedback = 1; 
 
%% start the experiment loop, errors in this loop will be caught
try
    % get participant ID:
    [datFile, subCode, subPath] = getSubjectCode(expCode);
    
    % prepare the screens    
    setScreens;
                                                                                
    % generate design 
    genDesign(subCode);
    
    % prepare the stimuli
    prepStim;

    % Add experiment Info after OpenWindow so it's under the text generated by Screen
    fprintf('\nManualInhibition\n');
    HideCursor;
    
    % Configure DATAPixx/TOUCHPixx
    Datapixx('SetVideoMode', 0);                        % Normal passthrough
    Datapixx('EnableTouchpixx');                        % Turn on TOUCHPixx hardware driver
    Datapixx('SetTouchpixxStabilizeDuration', 0.01);    % stable coordinates in secs before recognising touch
    Datapixx('RegWrRd');

    calibrate_touchpixx();
       
    % Display Instructions:
    ListenChar(0);
    DrawFormattedText(visual.window, 'Welcome to the experiment', 'center', 200, visual.textColor);
    DrawFormattedText(visual.window, 'Press any key to start', 'center', 'center', visual.textColor);
    Screen('Flip',visual.window);
    KbPressWait;
    
    % initialize the block names
    b_i = 1;
    b = 1;
  
    %% run normal blocks
    
    for b = design.blockOrder
        
        data.block(b_i) = runBlock(b, b_i);
        b_i = b_i+1;
        settings.feedback = 0;
        
    end   
    DrawFormattedText(visual.window, 'Thanks for your participation', 'center', 'center', visual.textColor);
    Screen('Flip',visual.window);
    
catch me
    rethrow(me);
    reddUp; %#ok<UNRCH>
end
    
% save all the data
data_table = data2output(data);
writetable(data_table, sprintf('./Data/%s_dat.csv',design.vpcode));
save(datFile,'data');

% save the design
design_table = design2output(design);
writetable(design_table, sprintf('./Design/%s_des.csv',design.vpcode));
save(sprintf('./Design/%s_design.mat',design.vpcode),'design'); %

Datapixx('DisableTouchpixx');
Datapixx('Close'); %call the close command after closing the screens

WaitSecs(2);
ListenChar(1);
Eyelink('Shutdown');

ShowCursor;
expEnd = toc;

fprintf('This experiment lasted %i minutes', round(expEnd/60,0));
sca;
Screen('CloseAll');
